// Generated by gencpp from file check/AddTwoInts.msg
// DO NOT EDIT!


#ifndef CHECK_MESSAGE_ADDTWOINTS_H
#define CHECK_MESSAGE_ADDTWOINTS_H

#include <ros/service_traits.h>


#include <check/AddTwoIntsRequest.h>
#include <check/AddTwoIntsResponse.h>


namespace check
{

struct AddTwoInts
{

typedef AddTwoIntsRequest Request;
typedef AddTwoIntsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct AddTwoInts
} // namespace check


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::check::AddTwoInts > {
  static const char* value()
  {
    return "6a2e34150c00229791cc89ff309fff21";
  }

  static const char* value(const ::check::AddTwoInts&) { return value(); }
};

template<>
struct DataType< ::check::AddTwoInts > {
  static const char* value()
  {
    return "check/AddTwoInts";
  }

  static const char* value(const ::check::AddTwoInts&) { return value(); }
};


// service_traits::MD5Sum< ::check::AddTwoIntsRequest> should match 
// service_traits::MD5Sum< ::check::AddTwoInts > 
template<>
struct MD5Sum< ::check::AddTwoIntsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::check::AddTwoInts >::value();
  }
  static const char* value(const ::check::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::check::AddTwoIntsRequest> should match 
// service_traits::DataType< ::check::AddTwoInts > 
template<>
struct DataType< ::check::AddTwoIntsRequest>
{
  static const char* value()
  {
    return DataType< ::check::AddTwoInts >::value();
  }
  static const char* value(const ::check::AddTwoIntsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::check::AddTwoIntsResponse> should match 
// service_traits::MD5Sum< ::check::AddTwoInts > 
template<>
struct MD5Sum< ::check::AddTwoIntsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::check::AddTwoInts >::value();
  }
  static const char* value(const ::check::AddTwoIntsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::check::AddTwoIntsResponse> should match 
// service_traits::DataType< ::check::AddTwoInts > 
template<>
struct DataType< ::check::AddTwoIntsResponse>
{
  static const char* value()
  {
    return DataType< ::check::AddTwoInts >::value();
  }
  static const char* value(const ::check::AddTwoIntsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // CHECK_MESSAGE_ADDTWOINTS_H
